server:
  port: 8082 #le puse 8082 pq el 8080 está en jenkins
spring:
  security:
    oauth2:
      client:
        provider:
          oauth2:
            keycloak:
              issuer-uri: http://localhost:9191/realms/tingeso
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: s6YgMKJGKI2konHCtrQxAQyAnv3LyuZ8
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client
  application: 
    name: gateway-service
  cloud:
    gateway:
      default-filters: TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: autorizacion-service
          uri: lb://autorizacion-service
          predicates:
            - Path=/autorizacion/**
            
        - id: importar-service
          uri: lb://importar-service
          predicates:
            - Path=/asistencia/**

        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/** 
            
             
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/planilla/**  
            
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/empleado/**  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
