server:
  port: 8080 #le puse 8082 pq el 8080 está en jenkins
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: autorizacion-service
          uri: http://localhost:8181
          predicates:
            - Path=/autorizacion/**
        - id: datareloj-service
          uri: http://localhost:8003
          predicates:
            - Path=/datareloj/**
        - id: empleado-service
          uri: http://localhost:8002
          predicates:
            - Path=/empleado/**
        - id: justificativo-service
          uri: http://localhost:8282
          predicates:
            - Path=/justificativo/** 
        - id: oficinaRRHH-service
          uri: http://localhost:8005
          predicates:
            - Path=/oficinaRRHH/**        
        - id: sueldo-service
          uri: http://localhost:8006
          predicates:
            - Path=/sueldo/**                    
