server:
  port: 8080 #le puse 8082 pq el 8080 está en jenkins
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    security:
      oauth2:
        client:
          provider:
            oauth2:
              keycloak:
                issuer-uri: http://localhost:9191/realms/tingeso
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: s6YgMKJGKI2konHCtrQxAQyAnv3LyuZ8
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client
  gateway:
    default-filters: TokenRelay
    discovery:
      locator:
        enabled: true
    routes:
      - id: autorizacion-service
        uri: http://localhost:8181
        predicates:
          - Path=/autorizacion/**
      - id: importar-service
        uri: http://localhost:8484
        predicates:
          - Path=/asistencia/**
      - id: importar-service
        uri: http://localhost:8484
        predicates:
          - Path=/upload/**
      - id: empleado-service
        uri: http://localhost:8002
        predicates:
          - Path=/empleado/**
      - id: justificativo-service
        uri: http://localhost:8282
        predicates:
          - Path=/justificativo/** 
      - id: oficinaRRHH-service
        uri: http://localhost:8005
        predicates:
          - Path=/oficinaRRHH/**        
      - id: planila-service
        uri: http://localhost:8585
        predicates:
          - Path=/planilla/**
      - id: planila-service
        uri: http://localhost:8585
        predicates:
          - Path=/empleado/**
