server:
  port: 8082 #le puse 8082 pq el 8080 está en jenkins
spring:
  application: 
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: autorizacion-service
          uri: lb://autorizacion-service
          predicates:
            - Path=/autorizacion/**
            
        - id: importar-service
          uri: lb://importar-service
          predicates:
            - Path=/asistencia/**

        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/** 
            
             
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/planilla/**  
            
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/empleado/**  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
